export const USERS_LOADING = 'USERS_LOADING';
export const USERS_LOADED = 'USERS_LOADED';
export const USERS_LOAD_FAILED = 'USERS_LOAD_FAILED';
export const USER_DELETING = 'USER_DELETING';
export const USER_DELETED = 'USER_DELETED';
export const USER_DELETING_FAILED = 'USER_DELETING_FAILED';
export const USER_WIPE = 'USER_WIPE';
export const USERS_WIPE = 'USERS_WIPE';